language: cpp
sudo: required
dist: trusty

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

matrix:
  fast_finish: true
  
addons:
  apt:
    sources: 
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - clang-3.7
      - g++-5
      - gcc-5
      - cmake
      - cmake-data
      - libgl1-mesa-dev
      - xorg-dev
      - libfreetype6-dev
git:
  submodules: true


install:
  - cmake --version
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update ; brew install boost llvm freetype;brew outdated gcc || brew upgrade gcc ; brew outdated cmake || brew upgrade cmake ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make -j2
cache:
  apt: true

notifications:
  slack: byteforge-team:kisF1nc1JVGxnVtGQ4notBAG
